# -*- coding: utf-8 -*-
"""scraping_eva_jobs .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12h7uzTi1-w8mFNW8DjSutLEyGPEYVmxu

### Scraping
"""

!pip install selenium
!apt-get update # update packages
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("--headless")  # Run in background
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")

driver = webdriver.Chrome(options=chrome_options)

from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

# Load the page
driver.get("https://apply.workable.com/eva-pharma/?lng=en")
time.sleep(3)

# Click 'Show more' until it's gone
while True:
    try:
        show_more = driver.find_element(By.XPATH, '//button[contains(text(), "Show more")]')
        driver.execute_script("arguments[0].click();", show_more)
        time.sleep(2)
    except (NoSuchElementException, ElementClickInterceptedException):
        print("✅ All jobs loaded.")
        break

# Now get all job links
job_links = driver.find_elements(By.XPATH, "//section//a[contains(@href, '/eva-pharma/')]")
urls = list(set(link.get_attribute("href") for link in job_links))
print(f"✅ Found {len(urls)} job listings.")

print(urls)

import json
import re

job_data = []

for url in urls:
    driver.get(url)
    time.sleep(2)  # wait for content to load

    # Title
    try:
        title = driver.find_element(By.TAG_NAME, "h1").text.strip()

        # Clean location and remove "On-site", "Remote", or "Hybrid" if included
        try:
            location_parts = driver.find_elements(By.CSS_SELECTOR, "span.styles--2TdGW")
            valid_parts = [
                part.text.strip().strip(',')
                for part in location_parts
                if len(part.text.strip()) > 1
                  and not part.text.strip() in ["On-site", "Remote", "Hybrid"]
                  and not any(x in part.text for x in ["cookies", "ads", "traffic", "policy"])
            ]
            location = ", ".join(valid_parts)
        except NoSuchElementException:
            location = "Not specified"

        # Description: inside .section-wrapper .description
        try:
            desc_elem = driver.find_element(By.CSS_SELECTOR, "div.section-wrapper div.description")
            description = desc_elem.text.strip()
        except NoSuchElementException:
            description = "Not available"



        # Department
        try:
            department = driver.find_element(By.CSS_SELECTOR, 'span[data-ui="job-department"]').text.strip()
        except NoSuchElementException:
            department = "Unknown"

        # Work Type: On-site / Hybrid / Remote
        try:
            work_type = driver.find_element(By.CSS_SELECTOR, "strong.styles--2kqW6").text.strip()
        except NoSuchElementException:
            work_type = "Not specified"

        try:
            employment_type = driver.find_element(By.CSS_SELECTOR, 'span[data-ui="job-type"]').text.strip()
        except NoSuchElementException:
            employment_type = "Not specified"


        try:
            # Locate the requirements section using the unique data-ui attribute
            requirements_section = driver.find_element(By.CSS_SELECTOR, 'section[data-ui="job-requirements"] ul')

            # Find all list items inside the <ul>
            li_items = requirements_section.find_elements(By.TAG_NAME, 'li')

            # Extract and clean the text
            qualifications = [li.text.strip() for li in li_items if li.text.strip()]
        except NoSuchElementException:
            qualifications = []
        experience = "Not specified"
        for qual in qualifications:
            # Match patterns like "1-2 years", "2 years", "3+ years"
            match = re.search(r'(\d+)\s*(?:[-–to]+\s*(\d+))?\s*(\+)?\s*(?:years?|yrs?)\s+of\s+experience', qual, re.IGNORECASE)
            if match:
                min_exp = match.group(1)
                max_exp = match.group(2)
                plus = match.group(3)
                if max_exp:
                    experience = f"{min_exp}-{max_exp} years"
                elif plus:
                    experience = f"{min_exp}+ years"
                else:
                    experience = f"{min_exp} years"
                break

        try:
           # responsibilities_section = driver.find_element(By.CSS_SELECTOR, 'section[data-ui="job-responsibilities"] ul')
            responsibilities_section = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div/main/section[1]/div/ul')

            responsibility_items = responsibilities_section.find_elements(By.TAG_NAME, 'li')
            responsibilities = [li.text.strip() for li in responsibility_items if li.text.strip()]
        except NoSuchElementException:
            responsibilities = []




        job = {
            "title": title,
            "location": location,
            "work type": work_type,
            "Employment Type": employment_type,
            "department": department,  # We'll infer this later if possible
            "description": responsibilities,
            "qualifications": qualifications,     # Optional: parse from description
            "experience": experience
        }

        job_data.append(job)

    except Exception as e:
        print(f"❌ Error scraping {url}: {e}")

# Save data
with open("eva_jobs.json", "w") as f:
    json.dump(job_data, f, indent=2)

print(f"✅ Scraped {len(job_data)} jobs successfully.")

print(job_data)

"""### Json File"""

import json


# Method 1: Save to a file
with open('eva_jobs.json', 'w', encoding='utf-8') as f:
    json.dump(job_data, f, ensure_ascii=False, indent=4)

print("Data saved to eva_jobs.json")

# Method 2: Get as JSON string (for copying/display)
json_string = json.dumps(job_data, ensure_ascii=False, indent=4)
print("JSON string:")
print(json_string[:500] + "...")  # Print first 500 chars to avoid huge output

from google.colab import files
import json

# 1. Upload your JSON file
uploaded = files.upload()  # This will prompt you to select the file
filename = next(iter(uploaded.keys()))  # Get the uploaded filename

# 2. Load and count jobs
with open(filename, 'r', encoding='utf-8') as f:
    jobs = json.load(f)  # Load the JSON data
    job_count = len(jobs)  # Count the number of job entries

# 3. Display the result
print(f"✅ The JSON file contains {job_count} job listings")

"""## RAG

### Prepare data
"""

def generate_possible_questions(jobs_data):
    """
    jobs_data: list of dictionaries, each containing job info like title, location, experience, department, etc.
    Returns a list of possible user questions generated from job entries.
    """

    questions = []
    for job in jobs_data:
        title = job.get("title","") # Access 'title' using the dictionary key
        location = job.get("location", "")
        department = job.get("department", "")
        experience = job.get("experience", "")
        requirements = job.get("requirements", "")
        job_type = job.get("type", "")

        general_questions = [
        "What jobs are available for fresh graduates?",
        "Which roles do not require prior experience?",
        "Can I find remote jobs at EVA Pharma?",
        "What departments are currently hiring?",
        "What job opportunities are available at EVA Pharma?",
        "How can I apply to EVA Pharma?",
        "Are there internship opportunities available?",
        "Which jobs are suitable for someone with 1-2 years of experience?",
        "Is EVA Pharma hiring in Cairo?",
        "What is the hiring process like at EVA Pharma?",
        "Can you list jobs available for pharmacists?",
        "What roles are open for computer science graduates?",
        "Does EVA Pharma offer part-time positions?",
        "Where can I submit my CV for open roles?",
        "What are the benefits of working at EVA Pharma?",
        "Is English required for all roles?",
        "What is the work culture like at EVA Pharma?",
        ]



        questions.extend([
            # Title-focused
            f"What does a {title} do?",
            f"Can you explain the job description for the {title}?",
            f"Is {title} currently open for applications?",
            f"Who is hiring for the {title} role?",

            # Responsibilities
            f"What are the responsibilities of the {title}?",
            f"What are the main duties of a {title}?",
            f"What kind of tasks does the {title} involve?",
            f"What is expected from someone working as a {title}?",

            # Experience
            f"How many years of experience are required for the {title}?",
            f"Does the {title} require previous experience?",
            f"Is entry-level experience accepted for the {title}?",
            f"What level of experience is needed for the {title}?",

            # Qualifications / Requirements
            f"What qualifications are needed for the {title} role?",
            f"What skills are required for the {title}?",
            f"What degrees are required for the {title}?",
            f"Do I need a background in Pharmacy for the {title}?",
            f"What are the job requirements for the {title}?",
            f"Is certification required for the {title} job?",

            # Location
            f"Where is the {title} job located?",
            f"Is the {title} job available in {location}?",
            f"Is relocation required for the {title} role?",
            f"Can the {title} be done remotely?",

            # Department
            f"Which department does the {title} belong to?",
            f"What business unit is the {title} part of?",

            # Type / Contract
            f"Is the {title} job full-time or part-time?",
            f"What is the contract type for the {title}?",
            f"Is the {title} role permanent or temporary?",

            # Application process
            f"How can I apply for the {title} job?",
            f"Is there a deadline to apply for the {title}?",
            f"Do I need to submit a resume for the {title}?",

            # Misc / Human-like
            f"Is the {title} a good fit for recent graduates?",
            f"Would you recommend the {title} job for someone with 2 years of experience?",
            f"Does the {title} job come with training?",
            f"Are there growth opportunities in the {title} role?",
            f"What benefits are offered for the {title}?",
            f"What’s the expected salary for a {title}?",
            f"Does the {title} job involve travel?",
        ])


    return list(set(questions + general_questions))  # Remove duplicates

user_queries = generate_possible_questions(job_data)

# Print a few example queries
print("\n".join(user_queries[:50]))

import json

with open("eva_jobs.json") as f:
    jobs = json.load(f)

# Convert job entries to plain text format
documents = []
for job in jobs:
    text = f"""
    Title: {job['title']}
    Department: {job['department']}
    Location: {job['location']}
    Type: {job['Employment Type']}
    Experience: {job['experience']}
    Requirements: {' '.join(job['qualifications'])}
    """
    documents.append(text.strip())

print(documents)

"""### fuzzy match for query"""

!pip install rapidfuzz

from rapidfuzz import process

def fuzzy_correct(query, corpus, threshold=70):
    """
    Corrects the query by finding the closest sentence in the corpus based on fuzzy matching.
    If no match passes the threshold, returns the original query.
    """
    match, score, _ = process.extractOne(query, corpus)
    return match if score >= threshold else query

from sentence_transformers import SentenceTransformer, util

# Load model once
model = SentenceTransformer("all-MiniLM-L6-v2")

def semantic_correct(query, candidate_queries, top_k=1):
    query_embedding = model.encode(query, convert_to_tensor=True)
    candidate_embeddings = model.encode(candidate_queries, convert_to_tensor=True)

    # Compute cosine similarities
    scores = util.cos_sim(query_embedding, candidate_embeddings)[0]
    top_result = scores.topk(k=top_k)

    # Return the most semantically similar candidate
    return candidate_queries[top_result.indices[0]]

q="Show me jbs for fresh gradates"
corrected_query = semantic_correct(q, user_queries)
print(corrected_query)

#q="How mny yars of exprice are reqred for Nigeria Ara Supervsor role?"
#q="What IT positions are avalble?"
#q="Show me jbs for frsh gradates"
q="What jbs are availble for fresh gradutes?"
corrected_query = fuzzy_correct(q, user_queries)
print(corrected_query)

"""### Retrieval"""

!pip install sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import numpy as np

# Load a pre-trained model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Encode the cleaned text into embeddings
documents_embeddings = model.encode(documents)

print(documents_embeddings.shape)

import faiss

# Create a FAISS index
dimension = documents_embeddings.shape[1]  # Dimension of the embeddings
index = faiss.IndexFlatL2(dimension)  # L2 distance for similarity search
index.add(documents_embeddings)  # Add embeddings to the index

def retrieve(query, top_k=5):
    # Convert the query into an embedding
    query_embedding = model.encode([query])

    # Search the FAISS index for the most similar embeddings
    distances, indices = index.search(np.array(query_embedding), top_k)

    # Retrieve the corresponding cleaned text
    results = [documents[i] for i in indices[0]]

    # Filter results to ensure relevance (optional)
    relevant_results = [item for item in results if query.lower() in item.lower()]

    return relevant_results

"""### Generation"""

!pip install google-generativeai

!pip install ipywidgets
!jupyter nbextension enable --py widgetsnbextension

import ipywidgets as widgets
from IPython.display import display, clear_output, Markdown, HTML
import json

# Configure Gemini (your existing setup)
import google.generativeai as genai
genai.configure(api_key="AIzaSyCq88RrztITjPIbQU4cWLoEfFYwK-OBrKY")

# Your existing generate_response function (unchanged)
def generate_response(query, job_data):
    prompt = f"""
    You are EVA Pharma's career assistant chatbot. Provide helpful, professional responses
    about job opportunities using the following job data. Be specific and include key details
    when relevant. If no matching jobs are found, suggest alternatives.

    User Question: {query}

    Available Job Data:
    {job_data}

    Guidelines:
    - Highlight key requirements when asked about qualifications
    - Mention locations/departments when relevant
    - For experience queries, specify required years
    - Be concise but informative
    - Maintain a professional, helpful tone

    Response:
    """
    model = genai.GenerativeModel(model_name="gemini-1.5-flash")
    response = model.generate_content(prompt)
    return response.text

chat_memory = []  # List of (query, response) tuples

def generate_response_with_memory(query, job_data):
    # Build the conversation history context
    memory_context = ""
    for past_query, past_response in chat_memory:
        memory_context += f"User: {past_query}\nBot: {past_response}\n"

    # Now add the current query and job data
    prompt = f"""
You are EVA Pharma's career assistant chatbot. Provide helpful, professional responses
about job opportunities using the following job data. Be specific and include key details
when relevant. If no matching jobs are found, suggest alternatives.

Conversation History:
{memory_context}

User Question: {query}

Available Job Data:
{job_data}

Guidelines:
- Highlight key requirements when asked about qualifications
- Mention locations/departments when relevant
- For experience queries, specify required years
- Be concise but informative
- Maintain a professional, helpful tone

Response:
"""

    # Generate the response using Gemini
    model = genai.GenerativeModel(model_name="gemini-1.5-flash")
    response = model.generate_content(prompt)
    final_response = response.text

    # Save to memory
    chat_memory.append((query, final_response))

    return final_response

"""### Voice"""

!pip install SpeechRecognition pydub

from google.colab import files
import json

import subprocess
import os

def convert_mp3_to_wav_ffmpeg(input_path, output_path):
    try:
        command = ['ffmpeg', '-y', '-i', input_path, output_path]
        subprocess.run(command, check=True)
        return output_path
    except subprocess.CalledProcessError:
        return None

import speech_recognition as sr

def capture_voice_input_from_file(file_path):
    recognizer = sr.Recognizer()

    # If MP3, convert to WAV using ffmpeg
    if file_path.endswith(".mp3"):
        wav_path = file_path.replace(".mp3", ".wav")
        result = convert_mp3_to_wav_ffmpeg(file_path, wav_path)
        if not result:
            return "Error converting MP3 to WAV."
        file_path = wav_path

    try:
        with sr.AudioFile(file_path) as source:
            audio = recognizer.record(source)
            return recognizer.recognize_google(audio)
    except sr.UnknownValueError:
        return "Sorry, I could not understand the audio."
    except Exception as e:
        return f"Error during speech recognition: {e}"

!pip install gTTS
from IPython.display import Audio, display
from gtts import gTTS

def speak_response(text, filename="response.mp3"):
    try:
        tts = gTTS(text)
        tts.save(filename)
        display(Audio(filename, autoplay=True))
    except Exception as e:
        print("Error converting text to speech:", e)

"""### UI"""

# Load your job data (replace with your actual data)

# if i use all_jobs from json file it retrive more details about my question but if i use documents it just answer on my question only or it depend also on top_k
#with open('eva_jobs.json', 'r') as f:
 #   all_jobs = json.load(f)

# Custom CSS for better styling
style = """
<style>
.job-card {
    border-left: 4px solid #4285F4;
    padding: 12px;
    margin: 8px 0;
    background: #f8f9fa;
    border-radius: 4px;
}
.query-box {
    background: #FA9EBC;
    padding: 12px;
    border-radius: 8px;
    margin-bottom: 12px;
}
.response-box {
    background: #0B1957;
    padding: 12px;
    border-radius: 8px;
    margin-top: 12px;
}
</style>
"""
display(HTML(style))

# Create UI elements
query_input = widgets.Textarea(
    placeholder="Type your job search query here...",
    layout={'width': '100%', 'height': '80px'},
    style={'description_width': 'initial'}
)

submit_btn = widgets.Button(
    description="Get Job Results",
    button_style='success',
    icon='search',
    layout={'width': '200px'}
)

clear_btn = widgets.Button(
    description="Clear All",
    button_style='warning',
    icon='eraser',
    layout={'width': '200px'}
)

voice_btn = widgets.Button(
    description="🎙️ Speak Now",
    button_style='info',
    icon='microphone',
    layout={'width': '200px'}
)

output_area = widgets.Output()

# Event handlers
def on_submit(b):
    with output_area:
        query = query_input.value.strip()
        if not query:
            display(Markdown("**Please enter a question about EVA Pharma jobs**"))
            return

        display(HTML("<hr style='border: 1px solid #ccc;'>"))  # Optional separator
        display(HTML(f'<div class="query-box"><strong>🔍🎯:</strong> {query}</div>'))

        try:
            response = generate_response_with_memory(query, documents)
            display(HTML(f'<div class="response-box"><strong>EVA 🧠🤖:</strong><br>{response}</div>'))

            if getattr(on_submit, "from_voice", False):
                speak_response(response)
                on_submit.from_voice = False

        except Exception as e:
            display(Markdown(f"**Error:** {str(e)}"))


def on_clear(b):
    query_input.value = ""
    with output_area:
        clear_output()

def on_voice(b):
    with output_area:
        clear_output()
        display(Markdown("**Please upload your voice file (.wav or .mp3)**"))
        uploaded = files.upload()
        if uploaded:
            file_name = next(iter(uploaded))
            spoken_query = capture_voice_input_from_file(file_name)
            display(Markdown(f"**🗣️ Recognized speech:** `{spoken_query}`"))
            query_input.value = spoken_query
            on_submit.from_voice = True
            on_submit(None)  # Simulate clicking the submit button


# Assign handlers
submit_btn.on_click(on_submit)
clear_btn.on_click(on_clear)
voice_btn.on_click(on_voice)


# Layout
controls = widgets.HBox([submit_btn, clear_btn, voice_btn], layout={'justify_content': 'center'})
main_box = widgets.VBox([
    widgets.HTML("<h2 style='color:#F1E1D8'>EVA Pharma Career Assistant</h2>"),
    query_input,
    controls,
    output_area
], layout={'width': '90%', 'margin': '0 auto'})

# Display the UI
display(main_box)

# Instructions
display(Markdown("""


**Try asking:**
- What IT positions are available?
- Shw me jbs for frsh gradates (misspelling)
- What Oracle-related roles exist?
- List jobs in Cairo
- how to cook pasta (out of context)
- How many years of experience are required for Nigeria Area Supervisor role?
"""))

