# -*- coding: utf-8 -*-
"""EVA Pharma Career Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12h7uzTi1-w8mFNW8DjSutLEyGPEYVmxu

### Scraping
"""

!pip install selenium
!apt-get update # update packages
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("--headless")  # Run in background
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")

driver = webdriver.Chrome(options=chrome_options)

from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

# Load the page
driver.get("https://apply.workable.com/eva-pharma/?lng=en")
time.sleep(3)

# Click 'Show more' until it's gone
while True:
    try:
        show_more = driver.find_element(By.XPATH, '//button[contains(text(), "Show more")]')
        driver.execute_script("arguments[0].click();", show_more)
        time.sleep(2)
    except (NoSuchElementException, ElementClickInterceptedException):
        print("✅ All jobs loaded.")
        break

# Now get all job links
job_links = driver.find_elements(By.XPATH, "//section//a[contains(@href, '/eva-pharma/')]")
urls = list(set(link.get_attribute("href") for link in job_links))
print(f"✅ Found {len(urls)} job listings.")

print(urls)

import json
import re

job_data = []

for url in urls:
    driver.get(url)
    time.sleep(2)  # wait for content to load

    # Title
    try:
        title = driver.find_element(By.TAG_NAME, "h1").text.strip()

        # Clean location and remove "On-site", "Remote", or "Hybrid" if included
        try:
            location_parts = driver.find_elements(By.CSS_SELECTOR, "span.styles--2TdGW")
            valid_parts = [
                part.text.strip().strip(',')
                for part in location_parts
                if len(part.text.strip()) > 1
                  and not part.text.strip() in ["On-site", "Remote", "Hybrid"]
                  and not any(x in part.text for x in ["cookies", "ads", "traffic", "policy"])
            ]
            location = ", ".join(valid_parts)
        except NoSuchElementException:
            location = "Not specified"

        # Description: inside .section-wrapper .description
        try:
            desc_elem = driver.find_element(By.CSS_SELECTOR, "div.section-wrapper div.description")
            description = desc_elem.text.strip()
        except NoSuchElementException:
            description = "Not available"



        # Department
        try:
            department = driver.find_element(By.CSS_SELECTOR, 'span[data-ui="job-department"]').text.strip()
        except NoSuchElementException:
            department = "Unknown"

        # Work Type: On-site / Hybrid / Remote
        try:
            work_type = driver.find_element(By.CSS_SELECTOR, "strong.styles--2kqW6").text.strip()
        except NoSuchElementException:
            work_type = "Not specified"

        try:
            employment_type = driver.find_element(By.CSS_SELECTOR, 'span[data-ui="job-type"]').text.strip()
        except NoSuchElementException:
            employment_type = "Not specified"


        try:
            # Locate the requirements section using the unique data-ui attribute
            requirements_section = driver.find_element(By.CSS_SELECTOR, 'section[data-ui="job-requirements"] ul')

            # Find all list items inside the <ul>
            li_items = requirements_section.find_elements(By.TAG_NAME, 'li')

            # Extract and clean the text
            qualifications = [li.text.strip() for li in li_items if li.text.strip()]
        except NoSuchElementException:
            qualifications = []
        experience = "Not specified"
        for qual in qualifications:
            # Match patterns like "1-2 years", "2 years", "3+ years"
            match = re.search(r'(\d+)\s*(?:[-–to]+\s*(\d+))?\s*(\+)?\s*(?:years?|yrs?)\s+of\s+experience', qual, re.IGNORECASE)
            if match:
                min_exp = match.group(1)
                max_exp = match.group(2)
                plus = match.group(3)
                if max_exp:
                    experience = f"{min_exp}-{max_exp} years"
                elif plus:
                    experience = f"{min_exp}+ years"
                else:
                    experience = f"{min_exp} years"
                break

        try:
           # responsibilities_section = driver.find_element(By.CSS_SELECTOR, 'section[data-ui="job-responsibilities"] ul')
            responsibilities_section = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div/main/section[1]/div/ul')

            responsibility_items = responsibilities_section.find_elements(By.TAG_NAME, 'li')
            responsibilities = [li.text.strip() for li in responsibility_items if li.text.strip()]
        except NoSuchElementException:
            responsibilities = []




        job = {
            "title": title,
            "location": location,
            "work type": work_type,
            "Employment Type": employment_type,
            "department": department,  # We'll infer this later if possible
            "description": responsibilities,
            "qualifications": qualifications,     # Optional: parse from description
            "experience": experience
        }

        job_data.append(job)

    except Exception as e:
        print(f"❌ Error scraping {url}: {e}")

# Save data
with open("eva_jobs.json", "w") as f:
    json.dump(job_data, f, indent=2)

print(f"✅ Scraped {len(job_data)} jobs successfully.")

print(job_data)

"""### Json File"""

import json


# Method 1: Save to a file
with open('eva_jobs.json', 'w', encoding='utf-8') as f:
    json.dump(job_data, f, ensure_ascii=False, indent=4)

print("Data saved to eva_jobs.json")

# Method 2: Get as JSON string (for copying/display)
json_string = json.dumps(job_data, ensure_ascii=False, indent=4)
print("JSON string:")
print(json_string[:500] + "...")  # Print first 500 chars to avoid huge output

from google.colab import files
import json

# 1. Upload your JSON file
uploaded = files.upload()  # This will prompt you to select the file
filename = next(iter(uploaded.keys()))  # Get the uploaded filename

# 2. Load and count jobs
with open(filename, 'r', encoding='utf-8') as f:
    jobs = json.load(f)  # Load the JSON data
    job_count = len(jobs)  # Count the number of job entries

# 3. Display the result
print(f"✅ The JSON file contains {job_count} job listings")

"""## RAG

### Prepare data
"""

def generate_possible_questions(jobs_data):
    """
    jobs_data: list of dictionaries, each containing job info like title, location, experience, department, etc.
    Returns a list of possible user questions generated from job entries.
    """

    general_questions = [
        "What jobs are available for fresh graduates?",
        "Which roles do not require prior experience?",
        "Can I find remote jobs at EVA Pharma?",
        "What departments are currently hiring?",
        "What job opportunities are available at EVA Pharma?",
        "How can I apply to EVA Pharma?",
        "Are there internship opportunities available?",
        "Which jobs are suitable for someone with 1-2 years of experience?",
        "Is EVA Pharma hiring in Cairo?",
        "What is the hiring process like at EVA Pharma?",
        "Can you list jobs available for pharmacists?",
        "What roles are open for computer science graduates?",
        "Does EVA Pharma offer part-time positions?",
        "Where can I submit my CV for open roles?",
        "What are the benefits of working at EVA Pharma?",
        "Is English required for all roles?",
        "What is the work culture like at EVA Pharma?",
        ]

    questions = []

    for job in jobs_data:
        title = job.get("title","") # Access 'title' using the dictionary key
        location = job.get("location", "")
        department = job.get("department", "")
        experience = job.get("experience", "")
        requirements = job.get("requirements", "")
        job_type = job.get("type", "")

        questions.extend([
            # Title-focused
            f"What does a {title} do?",
            f"Can you explain the job description for the {title}?",
            f"Is {title} currently open for applications?",
            f"Who is hiring for the {title} role?",

            # Responsibilities
            f"What are the responsibilities of the {title}?",
            f"What are the main duties of a {title}?",
            f"What kind of tasks does the {title} involve?",
            f"What is expected from someone working as a {title}?",

            # Experience
            f"How many years of experience are required for the {title}?",
            f"Does the {title} require previous experience?",
            f"Is entry-level experience accepted for the {title}?",
            f"What level of experience is needed for the {title}?",

            # Qualifications / Requirements
            f"What qualifications are needed for the {title} role?",
            f"What skills are required for the {title}?",
            f"What degrees are required for the {title}?",
            f"Do I need a background in Pharmacy for the {title}?",
            f"What are the job requirements for the {title}?",
            f"Is certification required for the {title} job?",

            # Location
            f"Where is the {title} job located?",
            f"Is the {title} job available in {location}?",
            f"Is relocation required for the {title} role?",
            f"Can the {title} be done remotely?",

            # Department
            f"Which department does the {title} belong to?",
            f"What business unit is the {title} part of?",

            # Type / Contract
            f"Is the {title} job full-time or part-time?",
            f"What is the contract type for the {title}?",
            f"Is the {title} role permanent or temporary?",

            # Application process
            f"How can I apply for the {title} job?",
            f"Is there a deadline to apply for the {title}?",
            f"Do I need to submit a resume for the {title}?",

            # Misc / Human-like
            f"Is the {title} a good fit for recent graduates?",
            f"Would you recommend the {title} job for someone with 2 years of experience?",
            f"Does the {title} job come with training?",
            f"Are there growth opportunities in the {title} role?",
            f"What benefits are offered for the {title}?",
            f"What’s the expected salary for a {title}?",
            f"Does the {title} job involve travel?",
        ])


    return list(set(questions + general_questions))  # Remove duplicates

user_queries = generate_possible_questions(job_data)

# Print a few example queries
print("\n".join(user_queries[:50]))

import json

with open("eva_jobs.json") as f:
    jobs = json.load(f)

# Convert job entries to plain text format
documents = []
for job in jobs:
    text = f"""
    Title: {job['title']}
    Department: {job['department']}
    Location: {job['location']}
    Type: {job['Employment Type']}
    Experience: {job['experience']}
    Requirements: {' '.join(job['qualifications'])}
    """
    documents.append(text.strip())

print(documents)

"""### fuzzy match for query"""

!pip install rapidfuzz

from rapidfuzz import process

def fuzzy_correct(query, corpus, threshold=70):
    """
    Corrects the query by finding the closest sentence in the corpus based on fuzzy matching.
    If no match passes the threshold, returns the original query.
    """
    match, score, _ = process.extractOne(query, corpus)
    return match if score >= threshold else query

from sentence_transformers import SentenceTransformer, util

# Load model once
model = SentenceTransformer("all-MiniLM-L6-v2")

def semantic_correct(query, candidate_queries, top_k=1):
    query_embedding = model.encode(query, convert_to_tensor=True)
    candidate_embeddings = model.encode(candidate_queries, convert_to_tensor=True)

    # Compute cosine similarities
    scores = util.cos_sim(query_embedding, candidate_embeddings)[0]
    top_result = scores.topk(k=top_k)

    # Return the most semantically similar candidate
    return candidate_queries[top_result.indices[0]]

q="Show me jbs for fresh gradates"
corrected_query = semantic_correct(q, user_queries)
print(corrected_query)

#q="How mny yars of exprice are reqred for Nigeria Ara Supervsor role?"
#q="What IT positions are avalble?"
#q="Show me jbs for frsh gradates"
q="What jbs are availble for fresh gradutes?"
corrected_query = fuzzy_correct(q, user_queries)
print(corrected_query)

"""### Retrieval"""

!pip install sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import numpy as np

# Load a pre-trained model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Encode the cleaned text into embeddings
documents_embeddings = model.encode(documents)

print(documents_embeddings.shape)

import faiss

# Create a FAISS index
dimension = documents_embeddings.shape[1]  # Dimension of the embeddings
index = faiss.IndexFlatL2(dimension)  # L2 distance for similarity search
index.add(documents_embeddings)  # Add embeddings to the index

def retrieve(user_input: str, all_jobs, top_k=5):
    try:
        # Get query embedding
        query_embedding = model.encode([user_input])

        # Ensure it's the right format for FAISS
        if isinstance(query_embedding, list):
            query_embedding = np.array([query_embedding], dtype=np.float32)
        else:
            query_embedding = np.array([[query_embedding]], dtype=np.float32)

        # Make sure top_k is an integer
        top_k = int(top_k)

        # Search
        distances, indices = index.search(query_embedding, top_k)
        # Return relevant documents
        retrieved_docs = []
        for i in indices[0]:
            if i < len(all_jobs):
                retrieved_docs.append(all_jobs[i])

        return retrieved_docs

    except Exception as e:
        print(f"Error in retrieve function: {str(e)}")
        # Return empty list or some default jobs
        return all_jobs[:3] if all_jobs else []

"""### Memory"""

# Conversation Memory Implementation
from collections import defaultdict
from datetime import datetime, timedelta
import threading

# Global conversation store - In production, use Redis or database
conversation_store = defaultdict(list)
store_lock = threading.Lock()

class ConversationMemory:
    def __init__(self, max_history=10, session_timeout_minutes=30):
        self.max_history = max_history
        self.session_timeout = timedelta(minutes=session_timeout_minutes)

    def get_session_id(self, request_info=None):
        """
        Generate session ID - you can customize this based on your needs
        For now, using a simple approach. In production, you might use:
        - IP address + User-Agent hash
        - JWT token user ID
        - Session cookies
        """
        # Simple fallback - use "default" session
        # You can enhance this by extracting session info from FastAPI request
        return "default_session"

    def add_message(self, session_id, user_message, bot_response):
        """Add a conversation turn to memory"""
        with store_lock:
            conversation_store[session_id].append({
                'timestamp': datetime.now(),
                'user': user_message,
                'assistant': bot_response
            })

            # Keep only recent messages
            if len(conversation_store[session_id]) > self.max_history:
                conversation_store[session_id] = conversation_store[session_id][-self.max_history:]

    def get_conversation_history(self, session_id):
        """Get recent conversation history"""
        with store_lock:
            if session_id not in conversation_store:
                return []

            # Filter out old conversations
            now = datetime.now()
            recent_messages = [
                msg for msg in conversation_store[session_id]
                if now - msg['timestamp'] < self.session_timeout
            ]

            # Update store with filtered messages
            conversation_store[session_id] = recent_messages
            return recent_messages

    def format_history_for_prompt(self, session_id):
        """Format conversation history for the LLM prompt"""
        history = self.get_conversation_history(session_id)
        if not history:
            return ""

        formatted_history = "\n\nPrevious conversation context:\n"
        for msg in history[-5:]:  # Use last 5 exchanges to avoid token limits
            formatted_history += f"User: {msg['user']}\n"
            formatted_history += f"Assistant: {msg['assistant']}\n"

        return formatted_history

# Initialize memory component
memory = ConversationMemory(max_history=10, session_timeout_minutes=30)

# Import required libraries
import numpy as np
import json
from sentence_transformers import SentenceTransformer
import faiss

# Initialize the model and index (add these if missing)
try:
    model = SentenceTransformer('all-MiniLM-L6-v2')
    # You'll need to load or create your FAISS index here
    # index = faiss.read_index("your_index_file.index")  # if you have a saved index
except Exception as e:
    print(f"Error initializing model: {e}")
    model = None

def load_jobs_from_json(filepath):
    """Load jobs from JSON file"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"Error loading jobs: {e}")
        return []

# Fixed retrieve function

# Configure Gemini - Move this to the top with other imports
import google.generativeai as genai

# Initialize Gemini
try:
    genai.configure(api_key="AIzaSyCq88RrztITjPIbQU4cWLoEfFYwK-OBrKY")
    print("Gemini API configured successfully")
except Exception as e:
    print(f"Error configuring Gemini: {e}")
    genai = None

"""### Generation"""

!pip install google-generativeai

!pip install ipywidgets
!jupyter nbextension enable --py widgetsnbextension

import ipywidgets as widgets
from IPython.display import display, clear_output, Markdown, HTML
import json

# Configure Gemini (your existing setup)
import google.generativeai as genai
genai.configure(api_key="#################################")

# Your existing generate_response function (unchanged)
def generate_response(query, job_data):
    prompt = f"""
    You are EVA Pharma's career assistant chatbot. Provide helpful, professional responses
    about job opportunities using the following job data. Be specific and include key details
    when relevant. If no matching jobs are found, suggest alternatives.

    User Question: {query}

    Available Job Data:
    {job_data}

    Guidelines:
    - Highlight key requirements when asked about qualifications
    - Mention locations/departments when relevant
    - For experience queries, specify required years
    - Be concise but informative
    - Maintain a professional, helpful tone

    Response:
    """
    model = genai.GenerativeModel(model_name="gemini-1.5-flash")
    response = model.generate_content(prompt)
    return response.text

"""### Voice"""

!pip install SpeechRecognition pydub

from google.colab import files
import json

!pip install gTTS
from IPython.display import Audio, display
from gtts import gTTS

from gtts import gTTS
from IPython.display import Audio, display
import subprocess
import os
import speech_recognition as sr

# Optional: import your RAG chatbot
# from my_chatbot_module import chatbot

def convert_audio_to_wav_ffmpeg(input_path, output_path):
    """Convert various audio formats (MP3, WebM, etc.) to WAV using ffmpeg"""
    try:
        command = [
            'ffmpeg', '-y', '-i', input_path,
            '-acodec', 'pcm_s16le',  # 16-bit PCM
            '-ar', '16000',          # 16kHz sample rate
            '-ac', '1',              # mono channel
            output_path
        ]
        subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return output_path
    except subprocess.CalledProcessError as e:
        print(f"FFmpeg error: {e.stderr.decode() if e.stderr else str(e)}")
        return None

def recognize_speech_from_audio(file_path):
    recognizer = sr.Recognizer()

    wav_path = os.path.splitext(file_path)[0] + "_converted.wav"
    result = convert_audio_to_wav_ffmpeg(file_path, wav_path)

    if not result:
        return None, "Error converting audio to WAV format supported by recognizer."

    try:
        with sr.AudioFile(wav_path) as source:
            audio = recognizer.record(source)
            recognized_text = recognizer.recognize_google(audio)
            return recognized_text, None
    except sr.UnknownValueError:
        return None, "Sorry, I could not understand the audio."
    except Exception as e:
        return None, f"Speech recognition error: {e}"

def generate_tts_response(text, filename="response.mp3"):
    try:
        tts = gTTS(text)
        tts.save(filename)
        return filename
    except Exception as e:
        return None

# ✅ All-in-one pipeline function
def voice_chatbot(audio_path: str) -> str:
    # Step 1: Speech-to-text
    recognized_text, error = recognize_speech_from_audio(audio_path)
    if error:
        raise Exception(error)

    print(f"[User said] → {recognized_text}")

    # Step 2: Get response from your chatbot
    response_text = chatbot(recognized_text)  # Replace with your RAG chatbot

    print(f"[Bot replied] → {response_text}")

    # Step 3: Convert response to speech
    response_audio_path = "response.mp3"
    result = generate_tts_response(response_text, response_audio_path)

    if not result:
        raise Exception("Failed to generate audio response.")

    return response_audio_path

"""### API"""

!pip install pyngrok

def load_jobs_from_json(path):
    with open(path, 'r') as f:
        return json.load(f)

from fastapi import FastAPI, UploadFile, File
from fastapi.responses import JSONResponse, FileResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pyngrok import ngrok
import nest_asyncio
import uvicorn
import os

# Allow FastAPI to run inside Jupyter Notebook
nest_asyncio.apply()

# Create the FastAPI app
app = FastAPI()

# Fix CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------- Define Request Model for Text Chat ----------
class TextRequest(BaseModel):
    text: str

# ---------- Dummy chatbot logic (replace this!) ----------
def chatbot(user_input: str) -> str:
    # Step 1: Load or scrape jobs (run this ONCE and cache if large)
    all_jobs = load_jobs_from_json("eva_jobs.json")  # or scrape_jobs()

    # Step 2: Retrieve relevant jobs
    retrieved_docs = retrieve(user_input, all_jobs)  # Return top-k matches

    # Step 3: Generate a response using LLM
    final_response = generate_response(user_input, retrieved_docs)

    return final_response


# ---------- Text Chat Endpoint ----------
@app.post("/chat-text")
async def chat_text_api(request: TextRequest):
    try:
        print(f"Received request: {request.text}")  # Debug log

        if not request.text:
            return JSONResponse(status_code=400, content={"error": "No text provided"})

        response_text = chatbot(request.text)
        print(f"Generated response: {response_text}")  # Debug log

        return {"response": response_text}

    except Exception as e:
        print(f"Error in chat_text_api: {str(e)}")
        import traceback
        traceback.print_exc()

        # Return a fallback response instead of crashing
        return {"response": "I apologize, but I'm experiencing technical difficulties right now. Please try asking about available positions or career opportunities at EVA Pharma."}

# ---------- Voice Chat Endpoint ----------
@app.post("/chat-voice")
async def chat_voice(audio: UploadFile = File(...)):
    try:
        # Save uploaded audio file
        audio_path = f"temp_{audio.filename}"
        with open(audio_path, "wb") as f:
            f.write(await audio.read())

        # Call your voice_chatbot logic
        response_audio_path = voice_chatbot(audio_path)

        # Return the generated audio file
        return FileResponse(response_audio_path, media_type="audio/mpeg")

    except Exception as e:
        return {"detail": f"Error processing audio: {str(e)}"}

# ---------- Set up ngrok ----------
NGROK_AUTH_TOKEN = "##############################"  # REPLACE THIS
ngrok.set_auth_token(NGROK_AUTH_TOKEN)
public_url = ngrok.connect(8000)
print("🚀 Public URL:", public_url)

# ---------- Run the FastAPI server ----------
uvicorn.run(app, port=8000)

