# -*- coding: utf-8 -*-
"""gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wm_H2D-TSLdKpKhpU-NOLTt5hlF1oduF
"""

# First, install the required packages
!pip install gradio>=4.0.0 requests>=2.28.0

import gradio as gr
import requests
import json

# Your API configuration
API_URL = "https://b5ac1dd9d92f.ngrok-free.app"  # Your FastAPI server
API_ENDPOINT = "/chat-text"  # Your text chat endpoint

class RAGClient:
    def __init__(self):
        self.api_url = API_URL
        self.endpoint = API_ENDPOINT

    def query(self, question):
        """
        Send query to your FastAPI RAG endpoint
        """
        try:
            # Prepare the request payload according to your TextRequest model
            payload = {
                "text": question
            }

            # Make the API call to your FastAPI endpoint
            response = requests.post(
                f"{self.api_url}{self.endpoint}",
                json=payload,
                headers={"Content-Type": "application/json"},
                timeout=30
            )

            if response.status_code == 200:
                result = response.json()
                return result.get("response", "No response received")
            else:
                return f"Error: API returned status code {response.status_code}"

        except requests.exceptions.ConnectionError:
            return "❌ Error: Cannot connect to the API. Make sure your FastAPI server is running!"
        except requests.exceptions.Timeout:
            return "⏰ Error: Request timed out. The API is taking too long to respond."
        except Exception as e:
            return f"⚠️ Error: {str(e)}"

# Initialize client
rag_client = RAGClient()

# Create the Gradio interface
def chat_interface(message, history):
    """Function that handles the chat interaction"""
    if not message.strip():
        return "Please enter a question."

    # Get response from your RAG API
    response = rag_client.query(message)
    return response

# Create the interface
demo = gr.ChatInterface(
    fn=chat_interface,
    title="🏥 EVA Pharma Career Assistant",
    description="Ask about job opportunities and positions at EVA Pharma",
    examples=[
        "What software engineering positions are available?",
        "Tell me about marketing roles at EVA Pharma",
        "What entry-level jobs do you have?",
        "Do you have remote work opportunities?",
        "What qualifications are needed for data science roles?"
    ],
    theme="soft"
)

# For Colab, we need to use a different launch method
# Launch the interface
demo.launch(debug=True, share=True)

